<a href="https://colab.research.google.com/github/tarundb2005-create/Machine-Learning/blob/main/RandomClassifier_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('Iris.csv')

In [6]:
df.shape

(150, 6)

In [7]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
X = df.drop('Species',axis = 1)
X

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [16]:
target = le.fit_transform(df.Species)

In [17]:
len(target)

150

In [18]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,target,test_size = 0.2)

In [26]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=70)
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=70)

In [27]:
model.score(X_test,y_test)

1.0

In [29]:
X_test

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
70    71            5.9           3.2            4.8           1.8
1      2            4.9           3.0            1.4           0.2
112  113            6.8           3.0            5.5           2.1
74    75            6.4           2.9            4.3           1.3
115  116            6.4           3.2            5.3           2.3
83    84            6.0           2.7            5.1           1.6
15    16            5.7           4.4            1.5           0.4
131  132            7.9           3.8            6.4           2.0
82    83            5.8           2.7            3.9           1.2
8      9            4.4           2.9            1.4           0.2
69    70            5.6           2.5            3.9           1.1
36    37            5.5           3.5            1.3           0.2
29    30            4.7           3.2            1.6           0.2
99   100            5.7           2.8            4.1           1.3
3      4            4.6           3.1            1.5           0.2
108  109            6.7           2.5            5.8           1.8
32    33            5.2           4.1            1.5           0.1
105  106            7.6           3.0            6.6           2.1
114  115            5.8           2.8            5.1           2.4
19    20            5.1           3.8            1.5           0.3
85    86            6.0           3.4            4.5           1.6
43    44            5.0           3.5            1.6           0.6
138  139            6.0           3.0            4.8           1.8
52    53            6.9           3.1            4.9           1.5
11    12            4.8           3.4            1.6           0.2
94    95            5.6           2.7            4.2           1.3
91    92            6.1           3.0            4.6           1.4
120  121            6.9           3.2            5.7           2.3
137  138            6.4           3.1            5.5           1.8
149  150            5.9           3.0            5.1           1.8

In [28]:
model.predict(X_test)

array([1, 0, 2, 1, 2, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 2, 0, 2, 2, 0, 1, 0,
       2, 1, 0, 1, 1, 2, 2, 2])